apiVersion: v1
kind: Service
metadata:
  name: zoo-headless
  labels:
    app: zookeeper
spec:
  clusterIP: None  # Headless Serviceë¡œ
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: follower
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
